-- Combined Supabase Migrations for Trending Juice
-- Generated on 2026-08-07T19:38:25.950Z

-- ==========================================
-- MIGRATION FILE: 20260628000000_initial_schema.sql
-- ==========================================

-- Reproducible base schema for the Trending Juice Restaurant OS.
-- This migration predates all feature and security migrations in this folder.

create extension if not exists pgcrypto;
create extension if not exists vector;

create table if not exists public.menu_categories (
  id bigint primary key,
  store_id text not null default 'trending-juice',
  name varchar(100) not null,
  icon varchar(50) not null default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint primary key,
  store_id text not null default 'trending-juice',
  category_id bigint references public.menu_categories(id) on delete set null,
  name varchar(100) not null,
  price numeric(12,2) not null default 0 check (price >= 0),
  is_available boolean not null default true,
  is_veg boolean not null default true,
  sort_order integer not null default 0,
  image_url varchar(500) not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.tables (
  id bigint primary key,
  store_id text not null default 'trending-juice',
  number integer not null,
  capacity integer not null default 2 check (capacity > 0),
  floor_section varchar(50) not null default 'Main',
  status varchar(20) not null default 'available',
  updated_at timestamptz not null default now(),
  unique (store_id, number)
);

create table if not exists public.staff (
  id bigint primary key,
  store_id text not null default 'trending-juice',
  auth_user_id uuid references auth.users(id) on delete set null,
  name varchar(100) not null,
  role varchar(30) not null check (role in ('developer','owner','manager','cashier','kitchen','waiter','delivery')),
  pin_hash varchar(64), -- deprecated; never granted to browser clients
  allow_express boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, auth_user_id)
);

create table if not exists public.staff_memberships (
  id bigint generated by default as identity primary key,
  store_id text not null default 'trending-juice',
  staff_id bigint references public.staff(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  role varchar(30) not null check (role in ('developer','owner','manager','cashier','kitchen','waiter','delivery')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, auth_user_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  store_id text not null default 'trending-juice',
  client_order_id uuid not null default gen_random_uuid(),
  idempotency_key text not null default gen_random_uuid()::text,
  order_number varchar(50) not null,
  display_token varchar(20),
  type varchar(20) not null default 'takeaway',
  status varchar(20) not null default 'pending',
  channel varchar(20) not null default 'pos',
  source varchar(20) not null default 'pos',
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12,2) not null default 0,
  tax numeric(12,2) not null default 0,
  tax_percent numeric(5,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  payment_method varchar(20),
  payment_status varchar(20) not null default 'unpaid',
  payment_reference text not null default '',
  payment_verified_at timestamptz,
  payment_verified_by text not null default '',
  payment_collected_at timestamptz,
  customer_name varchar(100) not null default '',
  customer_phone varchar(20) not null default '',
  delivery_address text not null default '',
  delivery_landmark text not null default '',
  delivery_notes text not null default '',
  delivery_status varchar(30) not null default 'none',
  delivery_staff_id bigint references public.staff(id) on delete set null,
  delivery_staff_name varchar(100) not null default '',
  delivery_assigned_at timestamptz,
  delivery_out_at timestamptz,
  delivered_at timestamptz,
  auth_user_id uuid references auth.users(id) on delete set null,
  staff_id bigint references public.staff(id) on delete set null,
  staff_name varchar(100) not null default '',
  table_id bigint references public.tables(id) on delete set null,
  notes text not null default '',
  requires_server_validation boolean not null default false,
  validation_status varchar(30) not null default 'trusted_staff',
  sync_attempts integer not null default 0,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (store_id, client_order_id),
  unique (store_id, idempotency_key),
  unique (store_id, order_number)
);

create table if not exists public.inventory (
  id bigint primary key,
  store_id text not null default 'trending-juice',
  name varchar(100) not null,
  quantity numeric(12,3) not null default 0,
  min_threshold numeric(12,3) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id bigint primary key,
  store_id text not null default 'trending-juice',
  name varchar(100) not null,
  contact varchar(150) not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.shifts (
  id bigint primary key,
  store_id text not null default 'trending-juice',
  staff_id bigint references public.staff(id) on delete cascade,
  clock_in varchar(50),
  clock_out varchar(50),
  date varchar(30),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_log (
  id bigint primary key,
  store_id text not null default 'trending-juice',
  timestamp timestamptz not null default now(),
  action varchar(150) not null,
  staff_name varchar(100) not null default 'System',
  details text not null default ''
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  store_id text not null default 'trending-juice',
  actor_staff_id bigint,
  actor_auth_user_id uuid,
  action text not null,
  target_table text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint primary key,
  store_id text not null default 'trending-juice',
  auth_user_id uuid references auth.users(id) on delete set null,
  name varchar(100) not null,
  phone varchar(20) not null,
  birthday varchar(30),
  total_spent numeric(12,2) not null default 0,
  visit_count integer not null default 0,
  loyalty_points integer not null default 0,
  tier varchar(20) not null default 'bronze',
  last_visit timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, phone)
);

create table if not exists public.recipes (
  id bigint primary key,
  store_id text not null default 'trending-juice',
  menu_item_id bigint not null references public.menu_items(id) on delete cascade,
  ingredients jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  unique (store_id, menu_item_id)
);

create table if not exists public.public_order_rate_limits (
  id bigint generated by default as identity primary key,
  store_id text not null default 'trending-juice',
  ip_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.document_embeddings (
  id uuid primary key default gen_random_uuid(),
  store_id text not null default 'trending-juice',
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(384) not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_menu_items_category_available on public.menu_items(store_id, category_id, is_available);
create index if not exists idx_orders_store_created on public.orders(store_id, created_at desc);
create index if not exists idx_orders_delivery on public.orders(store_id, type, delivery_status);
create index if not exists idx_staff_memberships_auth on public.staff_memberships(store_id, auth_user_id) where is_active;
create index if not exists idx_public_order_rate_limits_window on public.public_order_rate_limits(store_id, ip_hash, created_at desc);
create index if not exists idx_document_embeddings_hnsw on public.document_embeddings using hnsw (embedding vector_cosine_ops);

alter table public.menu_categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.tables enable row level security;
alter table public.staff enable row level security;
alter table public.staff_memberships enable row level security;
alter table public.orders enable row level security;
alter table public.inventory enable row level security;
alter table public.suppliers enable row level security;
alter table public.shifts enable row level security;
alter table public.activity_log enable row level security;
alter table public.audit_events enable row level security;
alter table public.customers enable row level security;
alter table public.recipes enable row level security;
alter table public.public_order_rate_limits enable row level security;
alter table public.document_embeddings enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.menu_categories, public.menu_items, public.tables to anon, authenticated;
grant select, insert, update, delete on public.menu_categories, public.menu_items, public.tables, public.suppliers, public.staff, public.staff_memberships, public.shifts, public.recipes to authenticated;
grant select, insert, update on public.orders, public.inventory, public.customers to authenticated;
grant select, insert on public.activity_log, public.audit_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "public active menu categories read" on public.menu_categories;
create policy "public active menu categories read" on public.menu_categories
  for select to anon, authenticated using (is_active);
drop policy if exists "public available menu items read" on public.menu_items;
create policy "public available menu items read" on public.menu_items
  for select to anon, authenticated using (is_available);
drop policy if exists "public read tables" on public.tables;
create policy "public read tables" on public.tables
  for select to anon, authenticated using (true);
drop policy if exists "staff memberships self read" on public.staff_memberships;
create policy "staff memberships self read" on public.staff_memberships
  for select to authenticated using (auth_user_id = (select auth.uid()) and is_active);

drop policy if exists "staff access menu_categories" on public.menu_categories;
create policy "staff access menu_categories" on public.menu_categories for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = menu_categories.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = menu_categories.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access menu_items" on public.menu_items;
create policy "staff access menu_items" on public.menu_items for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = menu_items.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = menu_items.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access orders" on public.orders;
create policy "staff access orders" on public.orders for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = orders.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = orders.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access tables" on public.tables;
create policy "staff access tables" on public.tables for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = tables.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = tables.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access inventory" on public.inventory;
create policy "staff access inventory" on public.inventory for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = inventory.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = inventory.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access suppliers" on public.suppliers;
create policy "staff access suppliers" on public.suppliers for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = suppliers.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = suppliers.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access staff" on public.staff;
create policy "staff access staff" on public.staff for select to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = staff.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access shifts" on public.shifts;
create policy "staff access shifts" on public.shifts for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = shifts.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = shifts.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access activity_log" on public.activity_log;
create policy "staff access activity_log" on public.activity_log for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = activity_log.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = activity_log.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access audit_events" on public.audit_events;
create policy "staff access audit_events" on public.audit_events for select to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = audit_events.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access customers" on public.customers;
create policy "staff access customers" on public.customers for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = customers.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = customers.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access recipes" on public.recipes;
create policy "staff access recipes" on public.recipes for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = recipes.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = recipes.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "customer self read write" on public.customers;
create policy "customer self read write" on public.customers for all to authenticated
  using (auth_user_id = (select auth.uid())) with check (auth_user_id = (select auth.uid()));
drop policy if exists "customer read own orders" on public.orders;
create policy "customer read own orders" on public.orders for select to authenticated
  using (auth_user_id = (select auth.uid()));

create or replace function public.consume_public_order_attempt(target_store_id text, target_ip_hash text, max_attempts integer, window_minutes integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare attempt_count integer;
begin
  perform pg_advisory_xact_lock(hashtextextended(target_store_id || ':' || target_ip_hash, 0));
  delete from public.public_order_rate_limits where created_at < now() - make_interval(mins => window_minutes);
  select count(*) into attempt_count from public.public_order_rate_limits
    where store_id = target_store_id and ip_hash = target_ip_hash and created_at >= now() - make_interval(mins => window_minutes);
  if attempt_count >= max_attempts then return false; end if;
  insert into public.public_order_rate_limits(store_id, ip_hash) values (target_store_id, target_ip_hash);
  return true;
end
$$;
revoke all on function public.consume_public_order_attempt(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_public_order_attempt(text, text, integer, integer) to service_role;

-- Kept only so the historical remediation migration can revoke it; the final
-- launch hardening migration removes this obsolete mock-payment function.
create or replace function public.emulate_stripe_webhook(order_client_id uuid, payment_intent_id text, status text)
returns boolean
language sql
security definer
set search_path = ''
as $$ select false $$;
revoke all on function public.emulate_stripe_webhook(uuid, text, text) from public, anon, authenticated;

create or replace function public.match_documents(query_embedding vector(384), match_threshold float, match_count integer, filter_store_id text)
returns table (id uuid, content text, metadata jsonb, similarity float)
language sql
stable
security definer
set search_path = ''
as $$
  select d.id, d.content, d.metadata, (1 - (d.embedding operator(public.<=>) query_embedding))::float
  from public.document_embeddings d
  where d.store_id = filter_store_id
    and 1 - (d.embedding operator(public.<=>) query_embedding) > match_threshold
  order by d.embedding operator(public.<=>) query_embedding
  limit least(greatest(match_count, 1), 20)
$$;
revoke all on function public.match_documents(vector, float, integer, text) from public, anon, authenticated;
grant execute on function public.match_documents(vector, float, integer, text) to service_role;

create or replace function public.prevent_ledger_modification()
returns trigger language plpgsql set search_path = '' as $$
begin raise exception 'Ledger records are immutable'; end
$$;
drop trigger if exists trg_prevent_mod_activity_log on public.activity_log;
create trigger trg_prevent_mod_activity_log before update or delete on public.activity_log
  for each row execute function public.prevent_ledger_modification();
drop trigger if exists trg_prevent_mod_audit_events on public.audit_events;
create trigger trg_prevent_mod_audit_events before update or delete on public.audit_events
  for each row execute function public.prevent_ledger_modification();

create or replace function public.prevent_order_deletion()
returns trigger language plpgsql set search_path = '' as $$
begin raise exception 'Orders cannot be deleted; cancel the order instead'; end
$$;
drop trigger if exists trg_prevent_delete_orders on public.orders;
create trigger trg_prevent_delete_orders before delete on public.orders
  for each row execute function public.prevent_order_deletion();

insert into storage.buckets (id, name, public)
values ('menu-images', 'menu-images', true)
on conflict (id) do update set public = excluded.public;
drop policy if exists "Allow public read access to menu images" on storage.objects;
create policy "Allow public read access to menu images" on storage.objects
  for select to anon, authenticated using (bucket_id = 'menu-images');
drop policy if exists "Allow staff to manage menu images" on storage.objects;
create policy "Allow staff to manage menu images" on storage.objects
  for all to authenticated
  using (bucket_id = 'menu-images' and exists (select 1 from public.staff_memberships sm where sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (bucket_id = 'menu-images' and exists (select 1 from public.staff_memberships sm where sm.auth_user_id = (select auth.uid()) and sm.is_active));

do $$
declare table_name text;
begin
  foreach table_name in array array['menu_categories','menu_items','orders','tables','inventory','suppliers','staff','staff_memberships','shifts','activity_log','customers','recipes']
  loop
    begin
      execute format('alter publication supabase_realtime add table %I', table_name);
    exception when duplicate_object then null; when undefined_object then null;
    end;
  end loop;
end
$$;


-- ==========================================
-- MIGRATION FILE: 202606290001_customer_platform_resources.sql
-- ==========================================

-- Customer platform resources: public offers plus authenticated customer-owned data.
-- Created manually because Supabase CLI is not installed in this workspace.

create table if not exists public.customer_offers (
  id uuid primary key default gen_random_uuid(),
  store_id text not null default 'trending-juice',
  code text not null,
  title text not null,
  label text,
  description text,
  display_value text,
  icon text default 'local_offer',
  customer_segment text default 'all',
  requires_auth boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, code)
);

create table if not exists public.customer_favorites (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  store_id text not null default 'trending-juice',
  menu_item_id bigint not null,
  item_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, store_id, menu_item_id)
);

create table if not exists public.customer_reviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  store_id text not null default 'trending-juice',
  order_id uuid,
  order_client_id text not null,
  rating integer not null check (rating between 1 and 5),
  comment text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, order_client_id)
);

create table if not exists public.customer_saved_addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  store_id text not null default 'trending-juice',
  label text not null default 'Home',
  address text not null,
  landmark text default '',
  latitude numeric,
  longitude numeric,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_notification_preferences (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  store_id text not null default 'trending-juice',
  preference_key text not null,
  enabled boolean not null default false,
  channel text not null default 'retention',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, store_id, preference_key)
);

alter table public.customer_offers enable row level security;
alter table public.customer_favorites enable row level security;
alter table public.customer_reviews enable row level security;
alter table public.customer_saved_addresses enable row level security;
alter table public.customer_notification_preferences enable row level security;

drop policy if exists "Anyone can read active customer offers" on public.customer_offers;
create policy "Anyone can read active customer offers"
on public.customer_offers
for select
to anon, authenticated
using (
  is_active = true
  and (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at >= now())
);

drop policy if exists "Customers read own favourites" on public.customer_favorites;
create policy "Customers read own favourites"
on public.customer_favorites
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Customers insert own favourites" on public.customer_favorites;
create policy "Customers insert own favourites"
on public.customer_favorites
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Customers update own favourites" on public.customer_favorites;
create policy "Customers update own favourites"
on public.customer_favorites
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Customers delete own favourites" on public.customer_favorites;
create policy "Customers delete own favourites"
on public.customer_favorites
for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Customers read own reviews" on public.customer_reviews;
create policy "Customers read own reviews"
on public.customer_reviews
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Customers insert own reviews" on public.customer_reviews;
create policy "Customers insert own reviews"
on public.customer_reviews
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Customers update own reviews" on public.customer_reviews;
create policy "Customers update own reviews"
on public.customer_reviews
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Customers read own saved addresses" on public.customer_saved_addresses;
create policy "Customers read own saved addresses"
on public.customer_saved_addresses
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Customers insert own saved addresses" on public.customer_saved_addresses;
create policy "Customers insert own saved addresses"
on public.customer_saved_addresses
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Customers update own saved addresses" on public.customer_saved_addresses;
create policy "Customers update own saved addresses"
on public.customer_saved_addresses
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Customers delete own saved addresses" on public.customer_saved_addresses;
create policy "Customers delete own saved addresses"
on public.customer_saved_addresses
for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Customers read own notification preferences" on public.customer_notification_preferences;
create policy "Customers read own notification preferences"
on public.customer_notification_preferences
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Customers insert own notification preferences" on public.customer_notification_preferences;
create policy "Customers insert own notification preferences"
on public.customer_notification_preferences
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Customers update own notification preferences" on public.customer_notification_preferences;
create policy "Customers update own notification preferences"
on public.customer_notification_preferences
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

grant select on public.customer_offers to anon, authenticated;
grant select, insert, update, delete on public.customer_favorites to authenticated;
grant select, insert, update on public.customer_reviews to authenticated;
grant select, insert, update, delete on public.customer_saved_addresses to authenticated;
grant select, insert, update on public.customer_notification_preferences to authenticated;

insert into public.customer_offers (store_id, code, title, label, description, display_value, icon, sort_order)
values
  ('trending-juice', 'BOOST', 'Power Boost', 'Juice Combo', 'Pair two fresh cold-pressed juices for a healthy energy kick.', 'Save ₹30', 'local_drink', 10),
  ('trending-juice', 'FUSION', 'Fruit Fusion', 'Best Seller', 'Mix & match any 3 small juices or shakes.', 'Save ₹50', 'blender', 20),
  ('trending-juice', 'REWARDS', 'Points on every order', 'Sip Club', 'Sign in before checkout and grow your rewards balance with every order.', 'Members', 'workspace_premium', 30)
on conflict (store_id, code) do update
set title = excluded.title,
    label = excluded.label,
    description = excluded.description,
    display_value = excluded.display_value,
    icon = excluded.icon,
    sort_order = excluded.sort_order,
    updated_at = now();


-- ==========================================
-- MIGRATION FILE: 202606300900_security_scan_remediation.sql
-- ==========================================

DROP POLICY IF EXISTS "Allow staff to manage menu images" ON storage.objects;
CREATE POLICY "Allow staff to manage menu images" ON storage.objects
  FOR ALL TO authenticated
  USING (bucket_id = 'menu-images' AND EXISTS (
    SELECT 1 FROM public.staff_memberships sm
    WHERE sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE
  ))
  WITH CHECK (bucket_id = 'menu-images' AND EXISTS (
    SELECT 1 FROM public.staff_memberships sm
    WHERE sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE
  ));

REVOKE ALL ON FUNCTION public.emulate_stripe_webhook(UUID, TEXT, TEXT) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.consume_public_order_attempt(target_store_id TEXT, target_ip_hash TEXT, max_attempts INTEGER, window_minutes INTEGER)
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE attempt_count INTEGER;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(target_store_id || ':' || target_ip_hash, 0));
  DELETE FROM public.public_order_rate_limits WHERE created_at < now() - make_interval(mins => window_minutes);
  SELECT count(*) INTO attempt_count FROM public.public_order_rate_limits
   WHERE store_id = target_store_id AND ip_hash = target_ip_hash AND created_at >= now() - make_interval(mins => window_minutes);
  IF attempt_count >= max_attempts THEN RETURN false; END IF;
  INSERT INTO public.public_order_rate_limits(store_id, ip_hash) VALUES (target_store_id, target_ip_hash);
  RETURN true;
END $$;
REVOKE ALL ON FUNCTION public.consume_public_order_attempt(TEXT, TEXT, INTEGER, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_public_order_attempt(TEXT, TEXT, INTEGER, INTEGER) TO service_role;

CREATE TABLE IF NOT EXISTS public.staff_pin_rate_limits (id BIGSERIAL PRIMARY KEY, store_id TEXT NOT NULL, ip_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE public.staff_pin_rate_limits ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.consume_staff_pin_attempt(target_store_id TEXT, target_ip_hash TEXT, max_attempts INTEGER, window_minutes INTEGER)
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE attempt_count INTEGER;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(target_store_id || ':' || target_ip_hash, 0));
  DELETE FROM public.staff_pin_rate_limits WHERE created_at < now() - make_interval(mins => window_minutes);
  SELECT count(*) INTO attempt_count FROM public.staff_pin_rate_limits
   WHERE store_id = target_store_id AND ip_hash = target_ip_hash AND created_at >= now() - make_interval(mins => window_minutes);
  IF attempt_count >= max_attempts THEN RETURN false; END IF;
  INSERT INTO public.staff_pin_rate_limits(store_id, ip_hash) VALUES (target_store_id, target_ip_hash);
  RETURN true;
END $$;
REVOKE ALL ON FUNCTION public.consume_staff_pin_attempt(TEXT, TEXT, INTEGER, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_staff_pin_attempt(TEXT, TEXT, INTEGER, INTEGER) TO service_role;


-- ==========================================
-- MIGRATION FILE: 202606301730_sync_gap_remediation.sql
-- ==========================================

-- Sync gap remediation: reservations table + realtime publication for missing tables.
-- Safe to run on an existing project. Idempotent (IF NOT EXISTS / ON CONFLICT).

-- ── 1. Reservations Table ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reservations (
  id BIGINT PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'trending-juice',
  table_id BIGINT REFERENCES tables(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  date VARCHAR(30) NOT NULL,
  time VARCHAR(30) NOT NULL,
  party_size INT DEFAULT 2,
  status VARCHAR(20) DEFAULT 'pending',
  notes TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON reservations TO authenticated;

DROP POLICY IF EXISTS "staff access reservations" ON reservations;
CREATE POLICY "staff access reservations" ON reservations
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = reservations.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE))
  WITH CHECK (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = reservations.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

-- ── 2. Add Missing Tables to Realtime Publication ──────────────────
-- Only adds tables that actually exist in the database (safe if customer
-- platform migration has not been applied yet).
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOREACH tbl IN ARRAY ARRAY['recipes','reservations','customer_offers','customer_favorites','customer_reviews']
  LOOP
    IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relname = tbl AND n.nspname = 'public') THEN
      BEGIN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE %I', tbl);
      EXCEPTION
        WHEN duplicate_object THEN NULL;
        WHEN undefined_object THEN NULL;
      END;
    END IF;
  END LOOP;
END $$;


-- ==========================================
-- MIGRATION FILE: 20260707164800_fix_orders_id_sequence.sql
-- ==========================================

-- Fix orders table id column auto-incrementing identity sequence
ALTER TABLE public.orders ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Resync sequence to the maximum existing order ID to prevent primary key conflicts
SELECT setval(pg_get_serial_sequence('public.orders', 'id'), COALESCE(MAX(id), 1)) FROM public.orders;

-- Create trigger function to automatically sync sequence on explicit ID inserts
CREATE OR REPLACE FUNCTION public.sync_orders_id_sequence()
RETURNS TRIGGER AS $$
DECLARE
  seq_name TEXT;
  curr_val BIGINT;
BEGIN
  IF NEW.id IS NOT NULL THEN
    seq_name := pg_get_serial_sequence('public.orders', 'id');
    IF seq_name IS NOT NULL THEN
      EXECUTE format('SELECT last_value FROM %s', seq_name) INTO curr_val;
      IF NEW.id > curr_val THEN
        EXECUTE format('SELECT setval(%L, %s)', seq_name, NEW.id);
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bind trigger to the orders table
DROP TRIGGER IF EXISTS trg_sync_orders_id_sequence ON public.orders;
CREATE TRIGGER trg_sync_orders_id_sequence
  BEFORE INSERT ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_orders_id_sequence();



-- ==========================================
-- MIGRATION FILE: 20260716154206_launch_security_hardening.sql
-- ==========================================

-- Production launch hardening.
-- The browser is untrusted: authorization, prices, payment state, loyalty,
-- inventory effects, and privileged staff data are enforced in Postgres.

create table if not exists public.store_security_settings (
  store_id text primary key,
  gst_percent numeric(5, 2) not null default 5.00 check (gst_percent between 0 and 30),
  delivery_fee numeric(10, 2) not null default 0.00 check (delivery_fee >= 0),
  updated_at timestamptz not null default now()
);
alter table public.store_security_settings enable row level security;
revoke all on table public.store_security_settings from anon, authenticated;
insert into public.store_security_settings (store_id, gst_percent, delivery_fee)
values ('trending-juice', 5.00, 0.00)
on conflict (store_id) do nothing;

-- PIN-only authentication is retired. Keep the legacy column nullable for a
-- rollback window, but never expose it through grants or application queries.
alter table public.staff alter column pin_hash drop not null;
alter table public.staff alter column pin_hash drop default;

create or replace function public.current_staff_role(target_store_id text)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select sm.role
  from public.staff_memberships sm
  where sm.store_id = target_store_id
    and sm.auth_user_id = (select auth.uid())
    and sm.is_active = true
  limit 1
$$;
revoke all on function public.current_staff_role(text) from public, anon;
grant execute on function public.current_staff_role(text) to authenticated, service_role;

create or replace function public.has_staff_role(target_store_id text, allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(public.current_staff_role(target_store_id) = any(allowed_roles), false)
$$;
revoke all on function public.has_staff_role(text, text[]) from public, anon;
grant execute on function public.has_staff_role(text, text[]) to authenticated, service_role;

-- Explicit grants are the first authorization layer; RLS below is the second.
revoke all on table
  public.menu_categories, public.menu_items, public.orders, public.tables,
  public.inventory, public.suppliers, public.staff, public.staff_memberships,
  public.shifts, public.activity_log, public.audit_events, public.customers,
  public.recipes, public.reservations, public.document_embeddings
from anon, authenticated;

grant select on table public.menu_categories, public.menu_items, public.tables to anon, authenticated;
grant insert, update, delete on table public.menu_categories, public.menu_items, public.tables to authenticated;
grant select, insert, update on table public.orders, public.inventory, public.customers to authenticated;
grant select, insert, update, delete on table public.suppliers, public.shifts, public.recipes, public.reservations to authenticated;
grant select, insert on table public.activity_log, public.audit_events to authenticated;
grant select on table public.staff_memberships to authenticated;
grant select (id, store_id, auth_user_id, name, role, allow_express, is_active, created_at, updated_at)
  on table public.staff to authenticated;

-- Replace broad policies with role- and ownership-aware policies.
drop policy if exists "staff access menu_categories" on public.menu_categories;
drop policy if exists "staff read menu_categories" on public.menu_categories;
drop policy if exists "managers write menu_categories" on public.menu_categories;
create policy "staff read menu_categories" on public.menu_categories
  for select to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager','cashier','kitchen','waiter','delivery']));
create policy "managers write menu_categories" on public.menu_categories
  for all to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager']))
  with check (public.has_staff_role(store_id, array['developer','owner','manager']));

drop policy if exists "staff access menu_items" on public.menu_items;
drop policy if exists "staff read menu_items" on public.menu_items;
drop policy if exists "managers write menu_items" on public.menu_items;
create policy "staff read menu_items" on public.menu_items
  for select to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager','cashier','kitchen','waiter','delivery']));
create policy "managers write menu_items" on public.menu_items
  for all to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager']))
  with check (public.has_staff_role(store_id, array['developer','owner','manager']));

drop policy if exists "staff access orders" on public.orders;
drop policy if exists "customer insert own orders" on public.orders;
drop policy if exists "staff read orders" on public.orders;
drop policy if exists "staff insert orders" on public.orders;
drop policy if exists "staff update orders" on public.orders;
create policy "staff read orders" on public.orders
  for select to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager','cashier','kitchen','waiter','delivery']));
create policy "staff insert orders" on public.orders
  for insert to authenticated
  with check (public.has_staff_role(store_id, array['developer','owner','manager','cashier','waiter']));
create policy "staff update orders" on public.orders
  for update to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager','cashier','kitchen','waiter','delivery']))
  with check (public.has_staff_role(store_id, array['developer','owner','manager','cashier','kitchen','waiter','delivery']));

drop policy if exists "staff access tables" on public.tables;
drop policy if exists "public read tables" on public.tables;
drop policy if exists "staff write tables" on public.tables;
create policy "public read tables" on public.tables
  for select to anon, authenticated using (true);
create policy "staff write tables" on public.tables
  for all to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager','cashier','waiter']))
  with check (public.has_staff_role(store_id, array['developer','owner','manager','cashier','waiter']));

drop policy if exists "staff access inventory" on public.inventory;
drop policy if exists "staff read inventory" on public.inventory;
drop policy if exists "managers write inventory" on public.inventory;
create policy "staff read inventory" on public.inventory
  for select to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager','cashier','kitchen']));
create policy "managers write inventory" on public.inventory
  for all to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager']))
  with check (public.has_staff_role(store_id, array['developer','owner','manager']));

drop policy if exists "staff access suppliers" on public.suppliers;
drop policy if exists "managers access suppliers" on public.suppliers;
create policy "managers access suppliers" on public.suppliers
  for all to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager']))
  with check (public.has_staff_role(store_id, array['developer','owner','manager']));

drop policy if exists "staff access staff" on public.staff;
drop policy if exists "staff read own profile" on public.staff;
drop policy if exists "managers read staff roster" on public.staff;
create policy "staff read own profile" on public.staff
  for select to authenticated
  using (auth_user_id = (select auth.uid()) and is_active = true);
create policy "managers read staff roster" on public.staff
  for select to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager']));

drop policy if exists "staff memberships self read" on public.staff_memberships;
create policy "staff memberships self read" on public.staff_memberships
  for select to authenticated
  using (auth_user_id = (select auth.uid()) and is_active = true);

drop policy if exists "staff access shifts" on public.shifts;
drop policy if exists "staff read shifts" on public.shifts;
drop policy if exists "staff write own shifts" on public.shifts;
create policy "staff read shifts" on public.shifts
  for select to authenticated
  using (
    public.has_staff_role(store_id, array['developer','owner','manager'])
    or exists (
      select 1 from public.staff s
      where s.id = shifts.staff_id and s.auth_user_id = (select auth.uid()) and s.is_active = true
    )
  );
create policy "staff write own shifts" on public.shifts
  for all to authenticated
  using (
    public.has_staff_role(store_id, array['developer','owner','manager'])
    or exists (
      select 1 from public.staff s
      where s.id = shifts.staff_id and s.auth_user_id = (select auth.uid()) and s.is_active = true
    )
  )
  with check (
    public.has_staff_role(store_id, array['developer','owner','manager'])
    or exists (
      select 1 from public.staff s
      where s.id = shifts.staff_id and s.auth_user_id = (select auth.uid()) and s.is_active = true
    )
  );

drop policy if exists "staff access activity_log" on public.activity_log;
drop policy if exists "staff insert activity_log" on public.activity_log;
drop policy if exists "managers read activity_log" on public.activity_log;
create policy "staff insert activity_log" on public.activity_log
  for insert to authenticated
  with check (public.has_staff_role(store_id, array['developer','owner','manager','cashier','kitchen','waiter','delivery']));
create policy "managers read activity_log" on public.activity_log
  for select to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager']));

drop policy if exists "staff access audit_events" on public.audit_events;
drop policy if exists "staff insert audit_events" on public.audit_events;
drop policy if exists "owners read audit_events" on public.audit_events;
create policy "staff insert audit_events" on public.audit_events
  for insert to authenticated
  with check (public.has_staff_role(store_id, array['developer','owner','manager','cashier','kitchen','waiter','delivery']));
create policy "owners read audit_events" on public.audit_events
  for select to authenticated
  using (public.has_staff_role(store_id, array['developer','owner']));

drop policy if exists "staff access customers" on public.customers;
drop policy if exists "customer self read write" on public.customers;
drop policy if exists "customer read own profile" on public.customers;
drop policy if exists "customer create own profile" on public.customers;
drop policy if exists "customer update own profile" on public.customers;
drop policy if exists "staff read customers" on public.customers;
drop policy if exists "staff write customers" on public.customers;
create policy "customer read own profile" on public.customers
  for select to authenticated using (auth_user_id = (select auth.uid()));
create policy "customer create own profile" on public.customers
  for insert to authenticated with check (auth_user_id = (select auth.uid()));
create policy "customer update own profile" on public.customers
  for update to authenticated
  using (auth_user_id = (select auth.uid()))
  with check (auth_user_id = (select auth.uid()));
create policy "staff read customers" on public.customers
  for select to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager','cashier','waiter','delivery']));
create policy "staff write customers" on public.customers
  for insert to authenticated
  with check (public.has_staff_role(store_id, array['developer','owner','manager','cashier','waiter']));
drop policy if exists "staff update customers" on public.customers;
create policy "staff update customers" on public.customers
  for update to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager','cashier','waiter']))
  with check (public.has_staff_role(store_id, array['developer','owner','manager','cashier','waiter']));

drop policy if exists "staff access recipes" on public.recipes;
drop policy if exists "staff read recipes" on public.recipes;
drop policy if exists "managers write recipes" on public.recipes;
create policy "staff read recipes" on public.recipes
  for select to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager','kitchen']));
create policy "managers write recipes" on public.recipes
  for all to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager']))
  with check (public.has_staff_role(store_id, array['developer','owner','manager']));

drop policy if exists "staff access reservations" on public.reservations;
drop policy if exists "staff manage reservations" on public.reservations;
create policy "staff manage reservations" on public.reservations
  for all to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager','cashier','waiter']))
  with check (public.has_staff_role(store_id, array['developer','owner','manager','cashier','waiter']));

drop policy if exists "staff access document_embeddings" on public.document_embeddings;
revoke all on table public.document_embeddings from anon, authenticated;

-- Customers may only review orders that belong to their authenticated account.
drop policy if exists "Customers insert own reviews" on public.customer_reviews;
drop policy if exists "Customers update own reviews" on public.customer_reviews;
create policy "Customers insert own reviews" on public.customer_reviews
  for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.orders o
      where o.store_id = customer_reviews.store_id
        and o.client_order_id::text = customer_reviews.order_client_id
        and o.auth_user_id = (select auth.uid())
        and o.status in ('completed','served')
    )
  );
create policy "Customers update own reviews" on public.customer_reviews
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.orders o
      where o.store_id = customer_reviews.store_id
        and o.client_order_id::text = customer_reviews.order_client_id
        and o.auth_user_id = (select auth.uid())
        and o.status in ('completed','served')
    )
  );

-- Prevent clients from setting loyalty balances or moving a profile between identities/stores.
create or replace function public.protect_customer_financial_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if pg_trigger_depth() > 1 or (select auth.uid()) is null then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.total_spent := 0;
    new.visit_count := 0;
    new.loyalty_points := 0;
    new.tier := 'bronze';
    new.last_visit := null;
  else
    if new.store_id is distinct from old.store_id
      or new.auth_user_id is distinct from old.auth_user_id then
      raise exception 'Customer identity and store are immutable';
    end if;
    if new.total_spent is distinct from old.total_spent
      or new.visit_count is distinct from old.visit_count
      or new.loyalty_points is distinct from old.loyalty_points
      or new.tier is distinct from old.tier
      or new.last_visit is distinct from old.last_visit then
      raise exception 'Customer financial and loyalty fields are server managed';
    end if;
  end if;
  new.updated_at := now();
  return new;
end
$$;
revoke all on function public.protect_customer_financial_fields() from public, anon, authenticated;
drop trigger if exists trg_protect_customer_financial_fields on public.customers;
create trigger trg_protect_customer_financial_fields
before insert or update on public.customers
for each row execute function public.protect_customer_financial_fields();

-- Rebuild every order line from the authoritative menu and enforce role-specific updates.
create or replace function public.enforce_order_integrity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_role text;
  raw_item jsonb;
  menu_row record;
  item_id bigint;
  item_quantity integer;
  validated_items jsonb := '[]'::jsonb;
  computed_subtotal numeric(12, 2) := 0;
  configured_tax numeric(5, 2) := 5.00;
  configured_delivery_fee numeric(10, 2) := 0.00;
begin
  caller_role := public.current_staff_role(new.store_id);

  if new.status not in ('pending','confirmed','preparing','ready','completed','cancelled') then
    raise exception 'Invalid order status';
  end if;
  if new.delivery_status not in ('none','pending','assigned','out_for_delivery','delivered','failed') then
    raise exception 'Invalid delivery status';
  end if;

  if tg_op = 'INSERT' or new.items is distinct from old.items then
    if jsonb_typeof(new.items) <> 'array'
      or jsonb_array_length(new.items) = 0
      or jsonb_array_length(new.items) > 40 then
      raise exception 'Order must contain between 1 and 40 line items';
    end if;

    for raw_item in select value from jsonb_array_elements(new.items)
    loop
      item_id := nullif(coalesce(raw_item->>'itemId', raw_item->>'id'), '')::bigint;
      item_quantity := nullif(raw_item->>'quantity', '')::integer;
      if item_id is null or item_quantity is null or item_quantity < 1 or item_quantity > 50 then
        raise exception 'Invalid order item or quantity';
      end if;

      select mi.id, mi.name, mi.price, mi.is_veg
      into menu_row
      from public.menu_items mi
      where mi.id = item_id and mi.store_id = new.store_id and mi.is_available = true;
      if not found then
        raise exception 'Menu item % is unavailable', item_id;
      end if;

      computed_subtotal := computed_subtotal + (menu_row.price * item_quantity);
      validated_items := validated_items || jsonb_build_array(jsonb_build_object(
        'itemId', menu_row.id,
        'itemName', menu_row.name,
        'price', menu_row.price,
        'quantity', item_quantity,
        'isVeg', menu_row.is_veg,
        'notes', left(coalesce(raw_item->>'notes', ''), 240)
      ));
    end loop;

    select s.gst_percent, s.delivery_fee
    into configured_tax, configured_delivery_fee
    from public.store_security_settings s
    where s.store_id = new.store_id;
    configured_tax := coalesce(configured_tax, 5.00);
    configured_delivery_fee := coalesce(configured_delivery_fee, 0.00);

    new.items := validated_items;
    new.subtotal := round(computed_subtotal, 2);
    new.tax_percent := configured_tax;
    new.tax := round(computed_subtotal * configured_tax / 100, 2);
    new.delivery_fee := case when new.type = 'delivery' then configured_delivery_fee else 0 end;
    new.total := new.subtotal + new.tax + new.delivery_fee;
    new.requires_server_validation := false;
    new.validation_status := 'accepted';
  end if;

  if tg_op = 'INSERT' then
    if new.type not in ('delivery','takeaway','dinein') then
      raise exception 'Invalid order type';
    end if;
    if new.channel not in ('pos','online','qr','express')
      or new.source not in ('pos','online','qr','express') then
      raise exception 'Invalid order channel';
    end if;
    if new.payment_method is not null and new.payment_method not in ('cash','upi') then
      raise exception 'Unsupported payment method';
    end if;
    if new.payment_status not in ('unpaid','pending','paid','partial','refunded','failed') then
      raise exception 'Invalid payment status';
    end if;
    if (select auth.uid()) is not null
      and new.payment_status in ('paid','partial')
      and caller_role not in ('developer','owner','manager','cashier') then
      raise exception 'Role % cannot confirm payment', coalesce(caller_role, 'customer');
    end if;
  else
    if new.store_id is distinct from old.store_id
      or new.client_order_id is distinct from old.client_order_id
      or new.idempotency_key is distinct from old.idempotency_key
      or new.order_number is distinct from old.order_number
      or new.type is distinct from old.type
      or new.channel is distinct from old.channel
      or new.source is distinct from old.source
      or new.auth_user_id is distinct from old.auth_user_id
      or new.items is distinct from old.items
      or new.subtotal is distinct from old.subtotal
      or new.tax is distinct from old.tax
      or new.tax_percent is distinct from old.tax_percent
      or new.delivery_fee is distinct from old.delivery_fee
      or new.total is distinct from old.total then
      raise exception 'Order identity, items, and totals are immutable';
    end if;

    if new.payment_method is not null and new.payment_method not in ('cash','upi') then
      raise exception 'Unsupported payment method';
    end if;
    if new.payment_status not in ('unpaid','pending','paid','partial','refunded','failed') then
      raise exception 'Invalid payment status';
    end if;

    if (new.payment_method is distinct from old.payment_method
      or new.payment_status is distinct from old.payment_status
      or new.payment_reference is distinct from old.payment_reference
      or new.payment_verified_at is distinct from old.payment_verified_at
      or new.payment_verified_by is distinct from old.payment_verified_by
      or new.payment_collected_at is distinct from old.payment_collected_at)
      and (select auth.uid()) is not null
      and caller_role not in ('developer','owner','manager','cashier') then
      raise exception 'Role % cannot modify payment state', coalesce(caller_role, 'customer');
    end if;

    if old.payment_status is distinct from new.payment_status then
      if old.payment_status = 'paid' and new.payment_status = 'refunded'
        and caller_role not in ('developer','owner','manager') then
        raise exception 'Role % cannot refund payments', coalesce(caller_role, 'customer');
      elsif old.payment_status in ('refunded','failed') then
        raise exception 'Terminal payment states cannot be changed';
      elsif old.payment_status = 'paid' and new.payment_status <> 'refunded' then
        raise exception 'Paid orders can only transition to refunded';
      end if;
    end if;
  end if;

  new.updated_at := now();
  return new;
end
$$;
revoke all on function public.enforce_order_integrity() from public, anon, authenticated;
drop trigger if exists trg_enforce_order_integrity on public.orders;
create trigger trg_enforce_order_integrity
before insert or update on public.orders
for each row execute function public.enforce_order_integrity();

-- Loyalty changes follow confirmed payment transitions, never profile input.
create or replace function public.apply_order_loyalty()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  points_delta integer := 0;
  spend_delta numeric(10, 2) := 0;
  visit_delta integer := 0;
begin
  if tg_op = 'INSERT' and new.payment_status = 'paid' then
    spend_delta := new.total;
    points_delta := floor(new.total)::integer;
    visit_delta := 1;
  elsif tg_op = 'UPDATE' and old.payment_status is distinct from 'paid' and new.payment_status = 'paid' then
    spend_delta := new.total;
    points_delta := floor(new.total)::integer;
    visit_delta := 1;
  elsif tg_op = 'UPDATE' and old.payment_status = 'paid' and new.payment_status in ('refunded','failed') then
    spend_delta := -old.total;
    points_delta := -floor(old.total)::integer;
    visit_delta := -1;
  else
    return new;
  end if;

  update public.customers c
  set total_spent = greatest(0, c.total_spent + spend_delta),
      visit_count = greatest(0, c.visit_count + visit_delta),
      loyalty_points = greatest(0, c.loyalty_points + points_delta),
      tier = case
        when greatest(0, c.loyalty_points + points_delta) >= 1000 then 'gold'
        when greatest(0, c.loyalty_points + points_delta) >= 500 then 'silver'
        else 'bronze'
      end,
      last_visit = case when spend_delta > 0 then now() else c.last_visit end,
      updated_at = now()
  where c.store_id = new.store_id
    and (
      (new.auth_user_id is not null and c.auth_user_id = new.auth_user_id)
      or (new.auth_user_id is null and new.customer_phone <> '' and c.phone = new.customer_phone)
    );
  return new;
end
$$;
revoke all on function public.apply_order_loyalty() from public, anon, authenticated;
drop trigger if exists trg_apply_order_loyalty on public.orders;
create trigger trg_apply_order_loyalty
after insert or update of payment_status on public.orders
for each row execute function public.apply_order_loyalty();

-- Inventory consumes only item IDs rebuilt by enforce_order_integrity.
create or replace function public.deduct_inventory_on_order()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  order_item record;
  recipe_ingredient record;
begin
  for order_item in
    select * from jsonb_to_recordset(new.items)
      as x("itemId" bigint, quantity integer)
  loop
    for recipe_ingredient in
      select ingredient."inventoryId", ingredient.quantity
      from public.recipes r
      cross join lateral jsonb_to_recordset(r.ingredients)
        as ingredient("inventoryId" bigint, quantity numeric)
      where r.store_id = new.store_id and r.menu_item_id = order_item."itemId"
    loop
      update public.inventory
      set quantity = greatest(0, quantity - (recipe_ingredient.quantity * order_item.quantity)),
          updated_at = now()
      where id = recipe_ingredient."inventoryId" and store_id = new.store_id;
    end loop;
  end loop;
  return new;
end
$$;
revoke all on function public.deduct_inventory_on_order() from public, anon, authenticated;
drop trigger if exists trg_deduct_inventory_on_order on public.orders;
create trigger trg_deduct_inventory_on_order
after insert on public.orders
for each row execute function public.deduct_inventory_on_order();

-- Remove the mock payment and obsolete PIN APIs entirely.
drop function if exists public.emulate_stripe_webhook(uuid, text, text);
drop function if exists public.consume_staff_pin_attempt(text, text, integer, integer);
drop table if exists public.staff_pin_rate_limits;

-- Replace the historical sequence trigger with a fixed-search-path version.
create or replace function public.sync_orders_id_sequence()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  seq_name text;
  curr_val bigint;
begin
  if new.id is not null then
    seq_name := pg_get_serial_sequence('public.orders', 'id');
    if seq_name is not null then
      execute format('select last_value from %s', seq_name) into curr_val;
      if new.id > curr_val then
        perform pg_catalog.setval(seq_name::regclass, new.id);
      end if;
    end if;
  end if;
  return new;
end
$$;
revoke all on function public.sync_orders_id_sequence() from public, anon, authenticated;

-- Storage writes are limited to menu managers and the known item path.
drop policy if exists "Allow staff to manage menu images" on storage.objects;
drop policy if exists "Managers manage menu images" on storage.objects;
create policy "Managers manage menu images" on storage.objects
  for all to authenticated
  using (
    bucket_id = 'menu-images'
    and name like 'items/%'
    and public.has_staff_role('trending-juice', array['developer','owner','manager'])
  )
  with check (
    bucket_id = 'menu-images'
    and name like 'items/%'
    and public.has_staff_role('trending-juice', array['developer','owner','manager'])
  );

-- Paid AI calls use an atomic, durable rate limit shared across Edge workers.
create index if not exists idx_audit_events_ai_rate_limit
  on public.audit_events(actor_auth_user_id, action, created_at desc);

create or replace function public.consume_staff_ai_attempt(
  target_auth_user_id uuid,
  target_store_id text,
  target_staff_id bigint,
  target_tier text,
  max_attempts integer,
  window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  attempt_count integer;
begin
  if target_auth_user_id is null or max_attempts < 1 or window_seconds < 1 then
    return false;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('staff-ai:' || target_auth_user_id::text, 0)
  );

  select count(*) into attempt_count
  from public.audit_events
  where actor_auth_user_id = target_auth_user_id
    and action = 'ai_chat_request'
    and created_at >= now() - pg_catalog.make_interval(secs => window_seconds);

  if attempt_count >= max_attempts then
    return false;
  end if;

  insert into public.audit_events(
    store_id, actor_staff_id, actor_auth_user_id, action, target_table, details
  ) values (
    target_store_id, target_staff_id, target_auth_user_id,
    'ai_chat_request', 'ai', pg_catalog.jsonb_build_object('tier', target_tier)
  );
  return true;
end
$$;
revoke all on function public.consume_staff_ai_attempt(uuid, text, bigint, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_staff_ai_attempt(uuid, text, bigint, text, integer, integer)
  to service_role;


-- ==========================================
-- MIGRATION FILE: 20260718000000_enforce_order_status_transitions.sql
-- ==========================================

-- Order lifecycle transitions are enforced in Postgres so a modified client
-- cannot cancel or reopen orders by bypassing the UI.
create or replace function public.enforce_order_status_transition()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_role text;
begin
  if new.status is not distinct from old.status then
    return new;
  end if;

  if old.status in ('completed', 'cancelled') then
    raise exception 'Terminal order status cannot be changed';
  end if;

  if not (
    (old.status = 'pending' and new.status in ('confirmed', 'cancelled'))
    or (old.status = 'confirmed' and new.status in ('preparing', 'cancelled'))
    or (old.status = 'preparing' and new.status in ('ready', 'cancelled'))
    or (old.status = 'ready' and new.status in ('completed', 'cancelled'))
  ) then
    raise exception 'Invalid order status transition from % to %', old.status, new.status;
  end if;

  if new.status = 'cancelled' then
    if old.payment_status = 'paid' then
      raise exception 'Paid orders must be refunded before cancellation';
    end if;

    if (select auth.uid()) is not null then
      caller_role := public.current_staff_role(new.store_id);
      if caller_role not in ('developer', 'owner', 'manager') then
        raise exception 'Role % cannot cancel orders', coalesce(caller_role, 'unknown');
      end if;
    end if;
  end if;

  return new;
end
$$;

revoke all on function public.enforce_order_status_transition() from public, anon, authenticated;

drop trigger if exists trg_enforce_order_status_transition on public.orders;
create trigger trg_enforce_order_status_transition
before update of status on public.orders
for each row execute function public.enforce_order_status_transition();


-- ==========================================
-- MIGRATION FILE: 20260727160620_launch_advisor_remediation.sql
-- ==========================================

-- Remove legacy policies and callable privileged helpers that predate the
-- repository migration ledger, and normalize pgvector outside public.

create schema if not exists extensions;
alter extension vector set schema extensions;

create or replace function public.match_documents(
  query_embedding extensions.vector(384),
  match_threshold float,
  match_count integer,
  filter_store_id text
)
returns table (id uuid, content text, metadata jsonb, similarity float)
language sql
stable
security definer
set search_path = ''
as $$
  select
    d.id,
    d.content,
    d.metadata,
    (1 - (d.embedding operator(extensions.<=>) query_embedding))::float
  from public.document_embeddings d
  where d.store_id = filter_store_id
    and 1 - (d.embedding operator(extensions.<=>) query_embedding) > match_threshold
  order by d.embedding operator(extensions.<=>) query_embedding
  limit least(greatest(match_count, 1), 20)
$$;
revoke all on function public.match_documents(extensions.vector, float, integer, text)
  from public, anon, authenticated;
grant execute on function public.match_documents(extensions.vector, float, integer, text)
  to service_role;

drop policy if exists "authenticated staff full access activity_log" on public.activity_log;
drop policy if exists "authenticated staff full access customers" on public.customers;
drop policy if exists "authenticated staff full access inventory" on public.inventory;
drop policy if exists "authenticated staff full access menu_categories" on public.menu_categories;
drop policy if exists "authenticated staff full access menu_items" on public.menu_items;
drop policy if exists "authenticated staff full access orders" on public.orders;
drop policy if exists "authenticated staff full access shifts" on public.shifts;
drop policy if exists "authenticated staff full access staff" on public.staff;
drop policy if exists "authenticated staff full access suppliers" on public.suppliers;
drop policy if exists "authenticated staff full access tables" on public.tables;

drop policy if exists "public menu categories read" on public.menu_categories;
drop policy if exists "public menu items read" on public.menu_items;
drop policy if exists "Allow public read access to menu images" on storage.objects;

create or replace function public.audit_order_changes()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  change_details jsonb;
begin
  if old.status is distinct from new.status
    or old.payment_status is distinct from new.payment_status
    or old.total is distinct from new.total
  then
    change_details := jsonb_build_object(
      'old_status', old.status,
      'new_status', new.status,
      'old_payment_status', old.payment_status,
      'new_payment_status', new.payment_status,
      'old_total', old.total::text,
      'new_total', new.total::text
    );

    insert into public.audit_events (
      store_id,
      actor_staff_id,
      actor_auth_user_id,
      action,
      target_table,
      target_id,
      details
    )
    values (
      new.store_id,
      new.staff_id,
      new.auth_user_id,
      'order_update',
      'orders',
      new.id::text,
      change_details
    );
  end if;

  return new;
end
$$;
revoke all on function public.audit_order_changes() from public, anon, authenticated;

do $$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    execute 'revoke all on function public.rls_auto_enable() from public, anon, authenticated';
  end if;
end $$;
drop function if exists public.prevent_modification();

drop index if exists public.idx_rate_limits_window;


-- ==========================================
-- MIGRATION FILE: 20260727161702_add_missing_foreign_key_indexes.sql
-- ==========================================

create index if not exists idx_customer_reviews_user_id
  on public.customer_reviews(user_id);

create index if not exists idx_customer_saved_addresses_user_id
  on public.customer_saved_addresses(user_id);

create index if not exists idx_recipes_menu_item_id
  on public.recipes(menu_item_id);

create index if not exists idx_reservations_customer_id
  on public.reservations(customer_id);

create index if not exists idx_reservations_table_id
  on public.reservations(table_id);

create index if not exists idx_shifts_staff_id
  on public.shifts(staff_id);

create index if not exists idx_staff_memberships_staff_id
  on public.staff_memberships(staff_id);


-- ==========================================
-- MIGRATION FILE: 20260729120000_restrict_developer_visibility.sql
-- ==========================================

-- Restrict developer account visibility on the staff roster.
--
-- Before this migration "managers read staff roster" granted developers, owners
-- and managers select on every row of public.staff, so a developer account was
-- readable by owners and managers even though only developers may modify it.
-- Hiding the row in the UI alone is not enough: the row still reaches the client
-- cache through the initial pull and through realtime postgres_changes, both of
-- which are evaluated against this select policy.
--
-- After this migration only developers can read developer rows. Every other role
-- sees the rest of the roster exactly as before, and the separate
-- "staff read own profile" policy still lets a developer read their own record.
--
-- The last-active-developer guard deliberately lives in the staff-admin edge
-- function rather than in a trigger here, mirroring the last-active-owner guard,
-- so that direct database access stays available as a recovery path.

drop policy if exists "managers read staff roster" on public.staff;
create policy "managers read staff roster" on public.staff
  for select to authenticated
  using (
    public.has_staff_role(store_id, array['developer', 'owner', 'manager'])
    and (
      staff.role <> 'developer'
      or public.has_staff_role(store_id, array['developer'])
    )
  );


-- ==========================================
-- MIGRATION FILE: 20260808000000_retenant_the_taste_to_trending_juice.sql
-- ==========================================

-- Re-tenant 'the-taste' -> 'trending-juice'.
--
-- The rebrand commit (d659e60) edited the `store_id` defaults inside migrations
-- that had already been applied. Editing an applied migration changes nothing on
-- a database that already ran it: `create table if not exists` is a no-op the
-- second time, so the live column defaults, the seeded rows and the storage
-- policies all stayed on 'the-taste' while the entire client moved to
-- 'trending-juice'. The client then queries a tenant that has no rows — staff
-- cannot sign in, and orders, menu, offers and telemetry all read empty.
--
-- This migration is the forward fix. It is deliberately idempotent and safe to
-- run against a database in any of three states:
--
--   * never provisioned      — the UPDATEs match nothing, the ALTERs re-assert
--                              defaults the create-table already set,
--   * provisioned on the old key — rows move across and defaults are corrected,
--   * already re-tenanted    — every statement is a no-op.
--
-- No explicit BEGIN/COMMIT, matching every other migration here: the Supabase
-- CLI already applies each file in its own transaction, so a failure part-way
-- rolls the whole thing back and leaves the tenant key consistent rather than
-- half-migrated. An explicit COMMIT would end that outer transaction early.

-- 1. Column defaults ---------------------------------------------------------
-- `set default` is unconditional, but `alter table` on a missing table aborts
-- the transaction, so each is guarded on the table existing. A store that never
-- ran the customer-platform migration should still get the core tables fixed.

do $$
declare
  t text;
  tables constant text[] := array[
    'activity_log',
    'audit_events',
    'customer_favorites',
    'customer_notification_preferences',
    'customer_offers',
    'customer_reviews',
    'customer_saved_addresses',
    'customers',
    'document_embeddings',
    'inventory',
    'menu_categories',
    'menu_items',
    'orders',
    'public_order_rate_limits',
    'recipes',
    'reservations',
    'shifts',
    'staff',
    'staff_memberships',
    'staff_pin_rate_limits',
    'store_security_settings',
    'suppliers',
    'tables'
  ];
begin
  foreach t in array tables loop
    if to_regclass('public.' || quote_ident(t)) is null then
      continue;
    end if;

    -- Only touch tables that actually carry the column. public_order_rate_limits
    -- and staff_pin_rate_limits declare store_id with no default; giving them one
    -- is harmless and keeps the tenant key uniform.
    if not exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = t and column_name = 'store_id'
    ) then
      continue;
    end if;

    execute format('alter table public.%I alter column store_id set default %L', t, 'trending-juice');
    execute format('update public.%I set store_id = %L where store_id = %L', t, 'trending-juice', 'the-taste');
  end loop;
end
$$;

-- 2. Storage policy ----------------------------------------------------------
-- 20260716154206_launch_security_hardening.sql:593 pins the tenant key as a
-- literal inside the menu-image storage policy rather than reading the row's
-- store_id, so an applied database still authorises against 'the-taste' and
-- every menu-image upload fails. `create policy` has no `if not exists`, so the
-- policy is dropped and recreated. The `name like 'items/%'` path constraint is
-- carried over verbatim — it is the other half of the rule and must not be lost.

do $$
begin
  if to_regclass('storage.objects') is null then
    return;
  end if;

  drop policy if exists "Managers manage menu images" on storage.objects;

  create policy "Managers manage menu images" on storage.objects
    for all to authenticated
    using (
      bucket_id = 'menu-images'
      and name like 'items/%'
      and public.has_staff_role('trending-juice', array['developer','owner','manager'])
    )
    with check (
      bucket_id = 'menu-images'
      and name like 'items/%'
      and public.has_staff_role('trending-juice', array['developer','owner','manager'])
    );
end
$$;

-- 3. Customer offers ---------------------------------------------------------
-- Two problems with the rows seeded by 202606290001, both of which reach the
-- customer:
--
--   * The codes were 'BOOST' and 'FUSION', but the client's FALLBACK_OFFERS
--     (src/services/customerPlatform.ts) advertises 'POWERBOOST' and
--     'FRUITFUSION'. fetchCustomerOffers falls back whenever the device is
--     offline or the query returns nothing, so which code a customer sees is
--     down to connectivity — and half the time staff cannot find it.
--
--   * display_value carried a hard rupee amount ('Save ₹30'). That field is the
--     prominent number on the offer card, and customerPlatform.ts:27-31 pins the
--     rule: the board price belongs in the description, because the server owns
--     eligibility and final price at checkout. A number there reads as a
--     guarantee the server has not made.
--
-- The seed is realigned with FALLBACK_OFFERS so both sources say the same thing.

do $$
begin
  if to_regclass('public.customer_offers') is null then
    return;
  end if;

  delete from public.customer_offers
  where store_id = 'trending-juice' and code in ('BOOST', 'FUSION');

  insert into public.customer_offers (store_id, code, title, label, description, display_value, icon, sort_order)
  values
    ('trending-juice', 'POWERBOOST', 'Power Boost', 'Combo favourite', 'Any juice plus any shake — ₹120 on the board.', 'Server validates at checkout', 'bolt', 10),
    ('trending-juice', 'FRUITFUSION', 'Fruit Fusion', 'Juice and a bite', 'Any juice with a fruit chaat on the side — ₹100 on the board.', 'Server validates at checkout', 'local_offer', 20),
    ('trending-juice', 'COOLDUO', 'Cool Duo', 'For two', 'Any shake plus a cold coffee — ₹110 on the board.', 'Server validates at checkout', 'groups', 30),
    ('trending-juice', 'REWARDS', 'Points on every order', 'Sip Club', 'Sign in before checkout and grow your rewards balance with every order.', 'Members', 'workspace_premium', 40)
  on conflict (store_id, code) do update
  set title = excluded.title,
      label = excluded.label,
      description = excluded.description,
      display_value = excluded.display_value,
      icon = excluded.icon,
      sort_order = excluded.sort_order;
end
$$;


-- ==========================================
-- MIGRATION FILE: 20260808120000_allow_temporary_staff_role.sql
-- ==========================================

-- Allow the 'temporary_staff' role to exist in the database.
--
-- The application has treated temporary_staff as a first-class role for a long
-- time: it is in STAFF_ROLES in src/services/authGuards.ts, main.ts routes to
-- it, Sidebar.tsx narrows the navigation for it, cloudDb.ts trims the pull for
-- it, and StaffView.tsx offers it in the Add Staff role picker. The two check
-- constraints written in the initial schema were never extended to match, so
-- the role could be chosen in the UI but never saved: the staff-admin edge
-- function's insert failed the constraint and the account was never created.
--
-- This only widens the set of accepted values; no existing row changes.
--
-- Note that temporary_staff is deliberately absent from the has_staff_role
-- allowlists in the RLS policies. That is the intended restriction — a
-- temporary staff member reads their own membership (the "staff memberships
-- self read" policy is role-agnostic, so sign-in works) and the public menu,
-- and nothing else. Granting them wider access is a product decision, not part
-- of making account creation work.

alter table public.staff
  drop constraint if exists staff_role_check;
alter table public.staff
  add constraint staff_role_check
  check (role in (
    'developer', 'owner', 'manager', 'cashier',
    'kitchen', 'waiter', 'delivery', 'temporary_staff'
  ));

alter table public.staff_memberships
  drop constraint if exists staff_memberships_role_check;
alter table public.staff_memberships
  add constraint staff_memberships_role_check
  check (role in (
    'developer', 'owner', 'manager', 'cashier',
    'kitchen', 'waiter', 'delivery', 'temporary_staff'
  ));


-- ==========================================
-- MIGRATION FILE: 20260808150000_store_branding_settings.sql
-- ==========================================

-- Store Branding & Custom Logo Table in Supabase
-- Stores cloud-synced logo, theme colors, banners, and social links per store.

create table if not exists public.store_branding (
  store_id text primary key default 'trending-juice',
  logo_url text not null default '',
  banner_url text not null default '',
  restaurant_name varchar(100) not null default 'Trending Juice',
  tagline varchar(200) not null default 'Fresh. Fun. You.',
  accent_color varchar(20) not null default '#FF9E1B',
  secondary_color varchar(20) not null default '#FF4D8D',
  bg_start varchar(20) not null default '#040406',
  bg_end varchar(20) not null default '#0B0B0F',
  kiosk_welcome text not null default '',
  kiosk_footer text not null default '',
  instagram text not null default '',
  facebook text not null default '',
  google_maps text not null default '',
  zomato text not null default '',
  swiggy text not null default '',
  whatsapp text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.store_branding enable row level security;

-- Allow public read access for customer storefronts, kiosks, and staff browsers
drop policy if exists "Public read store_branding" on public.store_branding;
create policy "Public read store_branding" on public.store_branding
  for select to public using (true);

-- Allow authenticated users to manage store branding
drop policy if exists "Authenticated manage store_branding" on public.store_branding;
create policy "Authenticated manage store_branding" on public.store_branding
  for all to authenticated using (true) with check (true);

-- Grant permissions
grant select on public.store_branding to anon, authenticated;
grant all on public.store_branding to service_role;

-- Seed default initial row for trending-juice
insert into public.store_branding (store_id, restaurant_name, tagline)
values ('trending-juice', 'Trending Juice', 'Fresh. Fun. You.')
on conflict (store_id) do nothing;


